### ISSUE TITLE
Alert Me Release Features List

### ISSUE THREAD

**Issue by honerlaw** [honerlaw/alert-me#1]
Version 1.0.0 *RELEASED*
- Change email to alertmemembers instead of honerlaw.io
- redirect to success page

Version 1.1.0 *RELEASED* - 12/1/2016
- Email automatically used when signed in
- Image / Title of product added to product list view

Version 1.1.1 *RELEASED* - 12/2/2016
- Login / Logout properly affects the content script forms
- Better error message for product watchers
- Modified some stylings slightly in the product list

Version 1.1.2 *RELEASED* - 12/12/2016
- Modify UI Slightly (changing background color in watchlist).
- Better handle HTTP errors

Version 2.0.0 *RELEASED* - 1/26/2017
- Conversion from Vertx to Spring and AngularDart to React
- Amazon Prime Form (Alert Me When Amazon Prime is Available)
- Multiple Forms of Notifications
  - SMS 
  - Email
- FireFox Support

Version 2.0.1 *RELEASED* - 1/28/2017
- Several minor bug fixes / UI tweaks

Version 2.1.0 *RELEASED* - 1/30/2017
- Price History graph on product page

Version 2.2.0
- Desktop Notifications (https://developer.chrome.com/extensions/desktop_notifications)
- Product lookup on each page (if it has been say 6 hours since the last price history lookup, lookup the product when the content script loads, otherwise do nothing). This is mainly a backend change to better gather information for each product.

**Comment by OnlineEmpireInc** [comment]
Testing 1.1.2...

I noticed I received a lot of email alerts this morning which is a great thing! however, we have a few issues with that too. Lets see if we can correct these two things:

1. Show image - then description link (this is so they know what product it was that price dropped)

2. The link being sent is not attaching our affiliate tag to it.

Let me know what you find out. I noticed we are starting to rank higher in the chrome store now and getting more users.

A quick turnaound on this will help us get better reviews which will either make us or break us in the very beginning.

Let me know what you find out. Thanks man!

**Comment by honerlaw** [comment]
I added a new ticket to handle the issues that you noticed as well as some issues that I noticed.

**Comment by OnlineEmpireInc** [comment]
I see those issues are fine. We can do the picture later. How's this stuff coming along?

Modify UI Slightly (changing background color in watchlist).
Version 1.2.0
Amazon Prime Form (Alert Me When Amazon Prime is Available)
Free Shipping Form (Alert Me When Free Shipping is Available)

Thanks man, its turning out good.

**Comment by honerlaw** [comment]
This was moved to google drive.
