### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by OnlineEmpireInc** [honerlaw/alert-me#24]
Hey Derek,

So this morning at work I tried to log into the ext. and I keep getting an "unknown error" and even if I try to request a new password, it gives me the same unknown error.

Can you please fix this asap or else I'm going to have to leave a bad 4 star review on our extension.

Thanks!

**Comment by OnlineEmpireInc** [comment]
Derek,

Just wondering when you can fix the small issues so I can create a walk through video? I was gonna make one, but figured I'd wait till the changes were finished.

**Comment by honerlaw** [comment]
They will be fixed sometime this weekend.
