### ISSUE TITLE
Not Sending Email Alert/Loading Issue

### ISSUE THREAD

**Issue by OnlineEmpireInc** [honerlaw/alert-me#5]
Hi Derek,

Well, good news is looks like were starting to get users. I know some are my friends and family but I think theyre are other just regular people using it now. I do see some clicks but need more users to get a better idea if its working and getting sales.

So, a couple issues I see...

1. When you are signed in, then close out the browser, or if you turn off your computer, then open the browser and click on the am button, it says loading, but never loads previous account. Should we just keep it from loading and have the sign-in form load instead?

2. Also, I did a test on a "Today's Deals" item, knowing that the price would go up in 19hours i set an alert for prices increases above $124.99 and an alert for price increases any amount.

Today I checked and the price is $498 and I didn't recieve an email for either alert that I set. Obviously this one is a major problem. I'm trying to think of a way to set an alert for a price decrease to test. Since thats the one we really care about.

**EDIT: I just found out a way to set a price decrease, I went to Today's Deals \ Watch Deals and started watching a product then went to the product page and set 3 alerts. So I'll let you know what I find out.**

Anyways let me know what you find out.

-Thanks.

**Comment by honerlaw** [comment]
I will look into this. I thought it was weird I wasn't getting emails either for my alerts. I am not sure if this is an issue with the scheduler or our mail service

**Comment by OnlineEmpireInc** [comment]
Have you been able to look into this?

**Comment by honerlaw** [comment]
I just pushed out a version that should work (we will find out tomorrow at 8am). I believe I fixed all of the issues that the scheduler was having.

I am looking into the login issue now.

**Comment by honerlaw** [comment]
Can you take a video of the issue for 1? or how to replicate it? I followed your instructions but it loaded up fine...

**Comment by OnlineEmpireInc** [comment]
Sorry, I tried making a video this morning, but it was working fine for me. Maybe you accidentally fixed it in the last version?? Brandon said it would happen to him as well., but I just tried it on my work computer as well and it works fine. Let me know when you get an email alert to show its working.

**Comment by OnlineEmpireInc** [comment]
Hey, while you're in there, can you make a small adjustment and have the background color on the watchlist to be all white?

**Comment by honerlaw** [comment]
I added a new ticket for the potential issue that could be causing the login / loading issue. I will add another ticket for dealing with the background color in the watchlist.

I am going to close this ticket now.
