### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by honerlaw** [honerlaw/alert-me#8]
Currently, the email notifications are sent out several times for the SAME product... This needs to be fixed to only notify once per user per product.

The next issue, is that the emails need to contain the name of the product, an image associated with the product, and the alert me affiliate tag.

Change send email from info@alertmemembers.com to <Alert Me Members> info@alertmemebers.com so that the side bar says Alert Me Members next to the email instead of info.

**Comment by OnlineEmpireInc** [comment]
Yeah I noticed I had a lot of email alerts but thought I just set a lot of alerts!

That all sounds good!

Is it just me or is this the same thing?

from info@alertmemembers.com to info@alertmemebers.com
