### ISSUE TITLE
Smartphone App

### ISSUE THREAD

**Issue by OnlineEmpireInc** [honerlaw/alert-me#9]
So, I know this is a totally separate project, but I think we should look at this sooner than later. From what I'm reading nearly 70% of all amazon sales happen through smartphones and tablets. Thats a BIG market.

If we even get a piece of the 30% that still use desktops/laptops, we could still do good, however I think we both know the market is moving to mobile everything.

What do you think about creating an alert me app? how long do you think it will take with the same features we have now?

What do you think about making one sooner than later? Are you up for it?

Let me know your thoughts...

**Comment by honerlaw** [comment]
It would take a decent amount of work to do.... and I don't see the benefit of having it this early? The mobile app would basically do what the popup does... Show you what products you are currently watching.

**Comment by OnlineEmpireInc** [comment]
Right, I mean we don't have to start really early. I was mainly suggesting the idea. Because right now, the user has to install the chrome browser, set alerts, but then can get the email on their phone and buy through their phone.

I was just things that if we had an app, then it would be like installing on their phone browser, they can set alerts the same way pretty much, then it will alert them through text messages.

But no hurry. Just an idea.

**Comment by honerlaw** [comment]
> I was just things that if we had an app, then it would be like installing on their phone browser, they can set alerts the same way pretty much, then it will alert them through text messages.

There is no functionality right now to tie directly into their phone browser. We could allow people to browse through our app though... but not sure the benefits of that (when we can just link them to products anyways and not have to worry about the complexity of maintaining a web browser in our app).

**Comment by OnlineEmpireInc** [comment]
Yeah, like our app will just open Amazon.com and they would just search amazon inside our app and at the bottom we could have the alert me box and then they can enter the same info as what we have them do in the extension right now, then text them & email when the item is in their price range.

> (when we can just link them to products anyways and not have to worry about the complexity of maintaining a web browser in our app)

I'm kinda confused by this....

**Comment by honerlaw** [comment]
This will basically behave the exact same as the extension (you can view and manage your account / watchers).

**Comment by honerlaw** [comment]
I don't believe this is currently in the scope of the extension. Maybe when the extension has gained traction and we have more money coming in / more time to develop it. Currently we should focus on delivering an excellent browser extension.
